### ISSUE TITLE
multiple charts on one page

### ISSUE THREAD

**Issue by KristerV** [perak/meteor-c3#1]
Hey. Great package. However I am unable to show multiple charts on one page.

``` Jade
p CHART 1
+c3 statsLast8
p CHART 2
+c3 statsLastMonth
p CHART 3
+c3 statsLastYear
```

only creates 
![screenshot_2015-07-21_15-43-13](https://cloud.githubusercontent.com/assets/2750622/8800910/43366b36-2fbf-11e5-8c6c-4aa0dd506944.png)

**Comment by KristerV** [comment]
there you go. Figured a PR out for ya :)

**Comment by perak** [comment]
Thank you dude! I'l merge it later, package is used in "meteor-kitchen" examples, so I need to change examples first to be functional with your fix.

**Comment by KristerV** [comment]
You should merge first and then figure out how to update your examples. I need to ship my app to a client and I'd be happy if I could include c3 as a downloadable pakage, not a local one.

**Comment by KristerV** [comment]
I'd like to add that even though it may not seem like it - people need this update. Nobody cares if the demo is not most current. They would rather have top-notch functionality in their hands than a top-notch demo demo.

**Comment by srault95** [comment]
```
<template name="mychart">
    <div id="{{chart_id}}"></div>
</template>

<template name="chart1">
    {{> mychart chart_id="chart1" data=data}}
</template>

<template name="chart2">
    {{> mychart chart_id="chart2" data=data}}
</template>

<template name="dashboard">
          <div class="row">
            <div class="column">
              {{> chart1}}
            </div>
            <div class="column">
              {{> chart2}}
            </div>
          </div>        
</template>
```

```
Template.mychart.onRendered(function() {
    var chart_id = this.data.chart_id || "chart";
    var chart = c3.generate(this.data.data || {bindto: '#'+chart_id, data: { columns: [] }});

    this.autorun(function (tracker) {
        if(Blaze.getData()) {
            chart.load(Blaze.getData().data.data || { columns: [] });
        }
    });
});

Template.chart1.helpers({
    "data": function() {
        return {
            bindto: '#chart1',
            data: {
                columns: [
                    ['data1', 30, 200, 100, 400, 150, 250],
                    ['data2', 130, 100, 140, 200, 150, 50],
                ],
                labels: true,
                type: 'spline'
            }
        };
    }   

Template.chart2.helpers({
    "data": function() {
        return {
            bindto: '#chart2',
            data: {
                columns: [
                    ['data1', 30, 200, 100, 400, 150, 250],
                    ['data2', 130, 100, 140, 200, 150, 50],
                    ['data3', 130, 100, 140, 200, 150, 50]
                ],
                labels: true,
                type: 'spline'
            }
        };
    }   

});

```

**Comment by perak** [comment]
In some reason, after merge chart is not reactive anymore (!?)

**Comment by perak** [comment]
@KristerV if data is passed like this `{{> c3 data=myData}}` it's not reactive. If data is passed like this `{{> c3 myData}}` it works normally (it's reactive).

**Comment by KristerV** [comment]
oh really? hmm. that doesn't make sense let me see..

**Comment by perak** [comment]
I am unable to try at the moment, but maybe we need to refer `UI.getData().data.data` inside autorun function to make it reactive.

**Comment by perak** [comment]
`chart.load(UI.getData().data || { columns: [] });` is where reactivity happens, and here we are passing `this.data` (actually reactive form of it: `UI.getData().data`) instead `this.data.data.data`

**Comment by perak** [comment]
@KristerV 

Thanks, fixed & closed.

**Comment by KristerV** [comment]
ahhaa, good work. I was working on a fix much more complicated - your's is sleek. And I tried it in my app - works great.
