### ISSUE TITLE
YAMLException: can not read a block mapping entry

### ISSUE THREAD

**Issue by nicbkw** [perak/meteor-c3#4]
I am trying to display multiple charts and followed the recommendation to add an id field:

`html: "<template name=\"TEMPLATE_NAME\">\n\t<h3>COMPONENT_TITLE</h3>\n\t{{> c3 data=SealevelPressure id="chart1"}}\n</template>\n"`

This throws the following error - please help me fix this :-)

```
*** Meteor Kitchen v0.9.57 ***
Meteor Application Generator - www.meteorkitchen.com
Copyright (c) Petar Korponaić
<petar.korponaic@gmail.com>

Converting yaml to json using "js-yaml"...
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 78, column 15:
                js: "Template.TEMPLATE_NAME.helper ...
```

Thanks!

**Comment by perak** [comment]
@nicbkw looks like malformed yaml. Try to escape quotes in id attribute: `id=\"...\"`

**Comment by nicbkw** [comment]
Perfect! - it works. Thanks so much for the rapid reply. Also, congratulations on Meteor Kitchen with YAML input - it's an excellent way to generate active web pages.

**Comment by perak** [comment]
@nicbkw glad you like it. If you find it useful - spread the word! :+1:
